import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import Layout from "@/components/Layout";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        Cum sociis natoque penatibus et magnis dis parturient montes, nascetur
        ridiculus mus. Etiam porta sem malesuada magna mollis euismod. Maecenas
        sed diam eget risus varius blandit sit amet non magna. Maecenas faucibus
        mollis interdum. Etiam porta sem malesuada magna mollis euismod. Integer
        posuere erat a ante venenatis dapibus posuere velit aliquet. Lorem ipsum
        dolor sit amet, consectetur adipiscing elit. Donec sed odio dui. Aenean
        lacinia bibendum nulla sed consectetur. Cras mattis consectetur purus
        sit amet fermentum. Maecenas faucibus mollis interdum. Nullam id dolor
        id nibh ultricies vehicula ut id elit. Sed posuere consectetur est at
        lobortis. Sed posuere consectetur est at lobortis. Lorem ipsum dolor sit
        amet, consectetur adipiscing elit. Cum sociis natoque penatibus et
        magnis dis parturient montes, nascetur ridiculus mus. Morbi leo risus,
        porta ac consectetur ac, vestibulum at eros. Maecenas sed diam eget
        risus varius blandit sit amet non magna. Duis mollis, est non commodo
        luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit.
        Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Nullam id
        dolor id nibh ultricies vehicula ut id elit. Donec ullamcorper nulla non
        metus auctor fringilla. Vivamus sagittis lacus vel augue laoreet rutrum
        faucibus dolor auctor. Donec ullamcorper nulla non metus auctor
        fringilla. Maecenas faucibus mollis interdum.
      </Layout>
    </>
  );
}
